from __future__ import annotations

import datetime as dt
from collections import defaultdict
from pathlib import Path
from typing import Iterable

from .models import ProcessedItem


class Notifier:
    """
    Output markdown files and issue body.
    输出 Markdown 及 Issue 正文，作为通知层（可对接 GitHub API）。
    """

    def __init__(self, digest_root: Path) -> None:
        self.digest_root = digest_root

    def write_daily_files(self, run_date: dt.date, items: Iterable[ProcessedItem]) -> dict:
        day_dir = self.digest_root / run_date.isoformat()
        day_dir.mkdir(parents=True, exist_ok=True)
        grouped = defaultdict(list)
        for it in items:
            if it.insight.category in {"ai_cli", "ai_agents", "ai_web", "ai_trending", "ai_hn"}:
                grouped[it.insight.category].append(it)
            else:
                # Keep output fixed to 5 files for portfolio requirement.
                # 为满足作品集要求，未知类别统一归入 ai_trending，保证输出文件恒定。
                grouped["ai_trending"].append(it)

        # Single beautiful digest file with 5 sections.
        # 单文件日报（五大板块），便于展示和面试讲解。
        digest_path = day_dir / "daily-digest.md"
        digest_content = self._render_single_digest(run_date, grouped)
        digest_path.write_text(digest_content, encoding="utf-8")

        issue = self._render_issue_index(run_date, digest_path)
        issue_path = self.digest_root / "latest_issue_body.md"
        issue_path.write_text(issue, encoding="utf-8")
        return {"dir": day_dir, "issue_body": issue_path, "digest_file": digest_path}

    def _render_single_digest(self, run_date: dt.date, grouped: dict) -> str:
        lines = [
            f"# AI Ecosystem Daily Digest | AI 生态每日报告 ({run_date.isoformat()})",
            "",
            "> A bilingual, interview-ready report generated from multi-source tracking.",
            "> 中英双语、多源聚合、可面试展示的日报样例。",
            "",
            "## 0) Executive Snapshot | 执行摘要",
            "",
            "- EN: Focuses on CLI tools, AI agents, web updates, trending repos, and HN community sentiment.",
            "- 中文：聚焦 CLI 工具、智能体生态、官网增量资讯、趋势仓库与社区情绪。",
            "",
            f"- Total processed items | 当日处理条数: **{sum(len(v) for v in grouped.values())}**",
            "",
        ]

        lines.extend(self._render_section("1) AI CLI", "AI CLI 工具动态", grouped.get("ai_cli", []), "release/pr/issue updates"))
        lines.extend(self._render_section("2) AI Agents", "智能体与 OpenClaw 赛道", grouped.get("ai_agents", []), "ecosystem collaboration and skills"))
        lines.extend(self._render_section("3) AI Web", "官网资讯与研究更新", grouped.get("ai_web", []), "official websites and research"))
        lines.extend(self._render_section("4) AI Trending", "趋势信号与主题标签", grouped.get("ai_trending", []), "GitHub trending and topics"))
        lines.extend(self._render_section("5) AI HN", "Hacker News 社区脉搏", grouped.get("ai_hn", []), "community hot discussions"))
        lines.append("")
        lines.append("---")
        lines.append("Generated by portfolio pipeline.")
        return "\n".join(lines) + "\n"

    def _render_section(self, en_title: str, zh_title: str, items: list[ProcessedItem], note: str) -> list[str]:
        lines = [
            f"## {en_title} | {zh_title}",
            "",
            f"- EN: {note}.",
            f"- 中文：{self._zh_note(note)}。",
            "",
        ]

        if not items:
            lines.extend(["- EN: No key updates today.", "- 中文：今日暂无关键更新。", ""])
            return lines

        # Use hybrid style: bullets + compact table for aesthetics/readability.
        # 混排：先要点列表，再给紧凑表格，不是全表格形式。
        top = items[:3]
        lines.append("### Highlights | 重点速览")
        for idx, it in enumerate(top, start=1):
            lines.append(
                f"{idx}. **{it.raw.title[:80]}**  \n"
                f"   - EN: {it.insight.summary_en[:140]}  \n"
                f"   - 中文：{it.insight.summary_zh[:140]}  \n"
                f"   - Source: [original]({it.raw.url})"
            )
        lines.append("")
        lines.extend(["### Structured View | 结构化视图", "", "| Type | Sentiment | Confidence | Link |", "|---|---|---:|---|"])
        for it in items[:8]:
            src_type = it.raw.metadata.get("kind", it.raw.source)
            lines.append(
                f"| {src_type} | {it.insight.sentiment} | {it.insight.confidence:.2f} | "
                f"[{it.raw.title[:36]}]({it.raw.url}) |"
            )
        lines.append("")
        return lines

    def _zh_note(self, note: str) -> str:
        mapping = {
            "release/pr/issue updates": "围绕发布、PR 和 Issue 的活跃变化",
            "ecosystem collaboration and skills": "关注生态协作、项目演进与 Skills 热度",
            "official websites and research": "聚合官网公告、研究和产品页面更新",
            "GitHub trending and topics": "结合 Trending 与主题标签提炼信号",
            "community hot discussions": "提取社区高热讨论并观察情绪",
        }
        return mapping.get(note, "关键更新摘要")

    def _render_issue_index(self, run_date: dt.date, digest_path: Path) -> str:
        day = run_date.isoformat()
        rel_path = f"digests/{day}/daily-digest.md"
        lines = [
            f"# AI Daily Digest ({day})",
            "",
            "Single-file bilingual report generated successfully.",
            "",
            f"- Report file: `{rel_path}`",
            f"- Open in repo: [daily-digest.md](./{rel_path})",
            "",
            "Sections included:",
            "- AI CLI",
            "- AI Agents",
            "- AI Web",
            "- AI Trending",
            "- AI HN",
        ]
        return "\n".join(lines) + "\n"
